sudo: required

language: node_js
node_js:
  - 10

services:
  - docker

before_install:
  - docker build -t kingo4luv/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kingo4luv/multi-docker npm test

after_success:
    - docker build -t kingo4luv/multi-client ./client
    - docker build -t kingo4luv/multi-nginx ./nginx
    - docker build -t kingo4luv/multi-server ./server
    - docker build -t kingo4luv/multi-worker ./worker

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password_stdin

- docker push kingo4luv/multi-client
- docker push kingo4luv/multi-nginx
- docker push kingo4luv/multi-server
- docker push kingo4luv/multi-worker

